export const SENDGRID_EVENT_WEBHOOK_PRIVATE_KEY = `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEILIwetvw8wNGT10dym9I1sDvUX/CZjj/pOw/13nXURL7oAoGCCqGSM49
AwEHoUQDQgAEFQxRBqzPGdIcDE6qjYWYdSJvTJRCZb+Yt9qCISJrMO7QA9jvtCbR
q1+FINwm8/e1lAtdYcQPs9N6hhgPoxkIsA==
-----END EC PRIVATE KEY-----`;

export const SENDGRID_EVENT_WEBHOOK_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFQxRBqzPGdIcDE6qjYWYdSJvTJRC
Zb+Yt9qCISJrMO7QA9jvtCbRq1+FINwm8/e1lAtdYcQPs9N6hhgPoxkIsA==
-----END PUBLIC KEY-----`;
